SCHEMA_VERSION = 1

RAW_WEATHER_TOPIC = "raw.weather"
RAW_AIRQUALITY_TOPIC = "raw.airquality"
RAW_EARTHQUAKE_TOPIC = "raw.earthquake"
NORMALIZED_EVENTS_TOPIC = "normalized.events"
ALERTS_TOPIC = "alerts"

CONSUMER_GROUP_NORMALIZATION = "normalization"
CONSUMER_GROUP_ALERTING = "alerting"
CONSUMER_GROUP_ANALYTICS = "analytics"

REQUIRED_TOPICS = (
    RAW_WEATHER_TOPIC,
    RAW_AIRQUALITY_TOPIC,
    RAW_EARTHQUAKE_TOPIC,
    NORMALIZED_EVENTS_TOPIC,
    ALERTS_TOPIC,
)

REQUIRED_CONSUMER_GROUPS = (
    CONSUMER_GROUP_NORMALIZATION,
    CONSUMER_GROUP_ALERTING,
    CONSUMER_GROUP_ANALYTICS,
)
